Repository kckaiwei/TurnMarker-alt, pull requests merged in 2021-01, with the labels that each got.

#12 [BUG] Fixing turn marker showing before combat
  dist/scripts/turnmarker.js
  dist/scripts/turnmarker.js.map
  src/scripts/turnmarker.js
Labels: bug

#14 [BUG] Fixing ghosting issues with some start markers
  dist/scripts/turnmarker.js
  dist/scripts/turnmarker.js.map
  src/scripts/marker.js
  src/scripts/turnmarker.js
Labels: bug

#19 [DOC] Updating dist folder and using manifest plus
  README.md
  dist/module.json
  dist/scripts/turnmarker.js
  dist/scripts/turnmarker.js.map
  src/module.json
Labels: documentation

#22 [BUG] Fix animated marker not pausing with game
  src/scripts/marker.js
  src/scripts/markeranimation.js
  src/scripts/settings.js
  src/scripts/turnmarker.js
Labels: bug

#23 Add missing async/awaits
  src/scripts/marker.js
Labels: bug

#25 [BUG] Fix start marker visibility regression
  src/scripts/marker.js
  src/scripts/settings.js
  src/scripts/turnmarker.js
Labels: bug

#34 [BUG] Fix deletion permissions on different scenes
  src/scripts/marker.js
  src/scripts/turnmarker.js
Labels: bug

#37 [BUG] Auto-size markers to stay 1:1 ratio
  src/scripts/marker.js
Labels: bug

#29 [FEATURE] Add on deck marker
  dist/scripts/turnmarker.js.map
  src/lang/en.json
  src/scripts/marker.js
  src/scripts/markeranimation.js
  src/scripts/settings.js
  src/scripts/settingsForm.js
  src/scripts/turnmarker.js
  src/scripts/utils.js
  src/templates/settings.html
Labels: enhancement
